export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_ACTIVATE_COMPANY_REQUEST = 'ADMIN_ACTIVATE_COMPANY_REQUEST'
export const ADMIN_ACTIVATE_COMPANY_SUCCESS = 'ADMIN_ACTIVATE_COMPANY_SUCCESS'
export const ADMIN_ACTIVATE_COMPANY_FAIL = 'ADMIN_ACTIVATE_COMPANY_FAIL'

export const ADMIN_BLACKLIST_RENTER_REQUEST = 'ADMIN_BLACKLIST_RENTER_REQUEST'
export const ADMIN_BLACKLIST_RENTER_SUCCESS = 'ADMIN_BLACKLIST_RENTER_SUCCESS'
export const ADMIN_BLACKLIST_RENTER_FAIL = 'ADMIN_BLACKLIST_RENTER_FAIL'

export const ADMIN_BLACKLIST_COMPANY_REQUEST = 'ADMIN_BLACKLIST_COMPANY_REQUEST'
export const ADMIN_BLACKLIST_COMPANY_SUCCESS = 'ADMIN_BLACKLIST_COMPANY_SUCCESS'
export const ADMIN_BLACKLIST_COMPANY_FAIL = 'ADMIN_BLACKLIST_COMPANY_FAIL'
