export const COMPANY_LOGIN_REQUEST = 'COMPANY_LOGIN_REQUEST'
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS'
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL'
export const COMPANY_LOGOUT = 'COMPANY_LOGOUT'

export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST'
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS'
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL'
export const COMPANY_LIST_RESET = 'COMPANY_LIST_RESET'

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST'
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS'
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL'
export const COMPANY_DETAILS_RESET = 'COMPANY_DETAILS_RESET'