export const COMPANY_LOGIN_REQUEST = 'COMPANY_LOGIN_REQUEST'
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS'
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL'
export const COMPANY_LOGOUT = 'COMPANY_LOGOUT'