export const COMPANY_LOGIN_REQUEST = 'COMPANY_LOGIN_REQUEST'
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS'
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL'
export const COMPANY_LOGOUT = 'COMPANY_LOGOUT'

export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST'
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS'
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL'
export const COMPANY_LIST_RESET = 'COMPANY_LIST_RESET'